scara: 

  #Publish all joint states 
  joint_state_controller: 
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position controllers
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: revolute_joint_1
    pid: {p: 100.0, i: 0.01, d: 80.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: revolute_joint_2
    pid: {p: 100.0, i: 0.01, d: 80.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic_joint_1
    pid: {p: 100.0, i: 0.01, d: 80.0}